"""Render docs/benchmark_mapping.md from taxonomy/benchmarks.yaml and results/suite_coverage.csv.

  python tools/coverage.py --matrix && python tools/render_catalog.py
"""
import csv
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from coverage import ARCH, ARCH_NAME, CAT, TASKS, coverage  # noqa: E402

SHORT = {"compact": "CMP", "short_gen": "SGEN", "long_reason": "LRSN", "long_gen": "LGEN", "sparse_retrieval": "RETR",
         "multi_hop": "MHOP", "aggregation": "AGG", "many_shot_icl": "ICL", "lc_code_struct": "CODE",
         "shared_context_multiturn": "MTURN", "agentic": "AGENT", "streaming_lm": "STRM"}
FACETS_SHOWN = ["growth", "dependency", "query", "fidelity", "reuse"]


def cell(x):
    return str(x).replace("|", "/").replace("\n", " ")


def main():
    lines = ["# Mapping benchmark suites onto the taxonomy",
             "",
             "*Generated by `tools/render_catalog.py` from [`taxonomy/benchmarks.yaml`](../taxonomy/benchmarks.yaml)"
             " (284 tasks) — do not edit by hand.*",
             "",
             "## How to map a suite",
             "",
             "```bash",
             "python tools/coverage.py --list-suites",
             "python tools/coverage.py --suite \"RULER\" --recommend 6      # coverage report + tasks that close the gaps",
             "python tools/coverage.py --tasks ruler:,scbench:retr-kv,aime   # any mix of task ids / suite prefixes",
             "python tools/coverage.py --custom my_benchmark.yaml            # a benchmark not in the catalog (facet values)",
             "python tools/coverage.py --suite \"L-Eval\" --alt              # count shared-context (multi-query) protocols",
             "```",
             "",
             "The **coverage score** weights requirements as follows:",
             "",
             "- each of the 12 archetypes: 3;",
             "- each growth / dependency / query value: 2;",
             "- each fidelity value and each stream-level reuse type: 1;",
             "- each composition value and each evidence position: 0.5.",
             "",
             "A suite scores 100% when it exercises every archetype and every facet value that matters for eviction.",
             "",
             "![suite coverage](../figures/fig6_suite_coverage.png)",
             "",
             "## Coverage matrix (tasks per archetype; key stressors)",
             "",
             "Column codes:",
             "",
             "- CMP = compact; SGEN = short-gen; LRSN = long-reason; LGEN = long-gen;",
             "- RETR = sparse retrieval; MHOP = multi-hop; AGG = aggregation; ICL = many-shot ICL;",
             "- CODE = long-context code & structured; MTURN = shared-context multi-turn; AGENT = agentic;",
             "  STRM = streaming LM.",
             "",
             "Stressor columns count tasks with decode-dominated growth, accumulating growth, deferred queries,",
             "exact high-entropy fidelity and persistent-constraint dependency.",
             "",
             (ROOT / "results" / "suite_coverage.md").read_text().strip(),
             "",
             "## Gaps of widely used suites",
             "",
             "| suite | missing archetypes | missing query / growth / dependency values |",
             "|---|---|---|"]
    for name in ["LongBench v1 (21)", "LongBench v2", "RULER", "InfiniteBench", "HELMET", "SCBench", "L-Eval",
                 "BABILong", "LoCoMo", "LongMemEval", "SnapKV-era standard (LongBench EN-16 + NIAH)",
                 "kvpress default evaluation", "Open LLM Leaderboard v2", "KVFundaBench", "Hold Onto That Thought",
                 "H2O (NeurIPS'23) evaluation", "StreamingLLM (ICLR'24) evaluation"]:
        tl = [TASKS[i] for i in CAT["suites"][name]]
        got, score, missing = coverage(tl)
        ma = [SHORT[v] for f, v in missing if f == "archetype"]
        mf = [f"{f}={v}" for f, v in missing if f in ("query", "growth", "dependency")]
        lines.append(f"| {name} ({score:.0%}) | {', '.join(ma) or '-'} | {', '.join(mf) or '-'} |")
    lines += ["",
              "## Full catalog",
              "",
              "Two kinds of evidence sit behind each row:",
              "",
              "- Facet values are assigned by the rules in `taxonomy/build_catalog.py`.",
              "- Lengths and metrics come from official repositories. The `conf` column is the confidence of those",
              "  source facts.",
              "",
              "A task marked † can additionally be run in shared-context mode (compress once, ask all its",
              "questions), which exercises `query=deferred`.",
              ""]
    by_suite = {}
    for t in CAT["tasks"]:
        by_suite.setdefault(t["suite"], []).append(t)
    for suite, ts in by_suite.items():
        lines += [f"### {suite}", "",
                  "| id | archetype | growth | dependency | query | fidelity | input | output | conf |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for t in ts:
            dag = "†" if t.get("alt") else ""
            lines.append(f"| `{t['id']}`{dag} | {SHORT[t['archetype']]} | {t['growth']} | {', '.join(t['dependency'])} | "
                         f"{t['query']} | {t['fidelity']} | {cell(t.get('input_len', ''))[:60]} | "
                         f"{cell(t.get('output_len', ''))[:50]} | {cell(t.get('confidence', '')).strip('[]')} |")
        lines.append("")
    out = ROOT / "docs" / "benchmark_mapping.md"
    out.write_text("\n".join(lines) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
